name: Build Docker Image & Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  docker-build-push-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Build Jar File
        run: mvn clean package -DskipTests


      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-demo:latest .


      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-demo:latest


      - name: Deploy on EC2 Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "ðŸš€ Pulling Latest Docker Image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-demo:latest

            echo "ðŸ›‘ Stop Old Container..."
            docker stop spring-boot-demo || true
            docker rm spring-boot-demo || true

            echo "âœ… Start New Container..."
            docker run -d \
              --name spring-boot-demo \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-demo:latest

            echo "ðŸŽ‰ Deployment Completed Successfully!"
